In [1]:
# Import Libraries

In [5]:
import pandas as pd
import seaborn as sns

### 1. Import the moovies dataset

# https://www.kaggle.com/carolzhangdc/imdb-5000-movie-dataset

In [10]:
movie=pd.read_csv("Desktop\movie_metadata.csv")
movie.head(20)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
7,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
9,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000
10,Color,Zack Snyder,673.0,183.0,0.0,2000.0,Lauren Cohan,15000.0,330249062.0,Action|Adventure|Sci-Fi,...,3018.0,English,USA,PG-13,250000000.0,2016.0,4000.0,6.9,2.35,197000
11,Color,Bryan Singer,434.0,169.0,0.0,903.0,Marlon Brando,18000.0,200069408.0,Action|Adventure|Sci-Fi,...,2367.0,English,USA,PG-13,209000000.0,2006.0,10000.0,6.1,2.35,0
12,Color,Marc Forster,403.0,106.0,395.0,393.0,Mathieu Amalric,451.0,168368427.0,Action|Adventure,...,1243.0,English,UK,PG-13,200000000.0,2008.0,412.0,6.7,2.35,0
13,Color,Gore Verbinski,313.0,151.0,563.0,1000.0,Orlando Bloom,40000.0,423032628.0,Action|Adventure|Fantasy,...,1832.0,English,USA,PG-13,225000000.0,2006.0,5000.0,7.3,2.35,5000
14,Color,Gore Verbinski,450.0,150.0,563.0,1000.0,Ruth Wilson,40000.0,89289910.0,Action|Adventure|Western,...,711.0,English,USA,PG-13,215000000.0,2013.0,2000.0,6.5,2.35,48000
15,Color,Zack Snyder,733.0,143.0,0.0,748.0,Christopher Meloni,15000.0,291021565.0,Action|Adventure|Fantasy|Sci-Fi,...,2536.0,English,USA,PG-13,225000000.0,2013.0,3000.0,7.2,2.35,118000
16,Color,Andrew Adamson,258.0,150.0,80.0,201.0,Pierfrancesco Favino,22000.0,141614023.0,Action|Adventure|Family|Fantasy,...,438.0,English,USA,PG,225000000.0,2008.0,216.0,6.6,2.35,0
17,Color,Joss Whedon,703.0,173.0,0.0,19000.0,Robert Downey Jr.,26000.0,623279547.0,Action|Adventure|Sci-Fi,...,1722.0,English,USA,PG-13,220000000.0,2012.0,21000.0,8.1,1.85,123000
18,Color,Rob Marshall,448.0,136.0,252.0,1000.0,Sam Claflin,40000.0,241063875.0,Action|Adventure|Fantasy,...,484.0,English,USA,PG-13,250000000.0,2011.0,11000.0,6.7,2.35,58000
19,Color,Barry Sonnenfeld,451.0,106.0,188.0,718.0,Michael Stuhlbarg,10000.0,179020854.0,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,...,341.0,English,USA,PG-13,225000000.0,2012.0,816.0,6.8,1.85,40000

### 2. Use crosstabs to show the number of moovies per country

In [24]:
pd.crosstab(movie.director_name, movie.country, margins=True, margins_name='Total')

country,Afghanistan,Argentina,Aruba,Australia,Bahamas,Belgium,Brazil,Bulgaria,Cambodia,Cameroon,...,Sweden,Switzerland,Taiwan,Thailand,Turkey,UK,USA,United Arab Emirates,West Germany,Total
director_name,,,,,,,,,,,,,,,,,,,,,
A. Raven Cruz,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
Aaron Hann,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
Aaron Schneider,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
Aaron Seltzer,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
Abel Ferrara,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Álex de la Iglesia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
Émile Gaudreault,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
Éric Tessier,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
Étienne Faure,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
Total,1,4,1,53,1,4,8,1,1,1,...,6,3,2,5,1,434,3733,1,3,4936

In [ ]:
pd.crosstab(movie.director_name, movie.country)

### 3. Create a crosstab to show the number of films per director and genre splitted by country

In [15]:
pd.crosstab(movie.director_name, movie.country)

country,Afghanistan,Argentina,Aruba,Australia,Bahamas,Belgium,Brazil,Bulgaria,Cambodia,Cameroon,...,Spain,Sweden,Switzerland,Taiwan,Thailand,Turkey,UK,USA,United Arab Emirates,West Germany
director_name,,,,,,,,,,,,,,,,,,,,,
A. Raven Cruz,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Aaron Hann,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Aaron Schneider,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Aaron Seltzer,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Abel Ferrara,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zoran Lisinac,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Álex de la Iglesia,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
Émile Gaudreault,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Éric Tessier,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Étienne Faure,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### 4. Average duration of filmes grouped by color

In [30]:
pd.crosstab(movie.duration, movie.color, margins=True, margins_name='Total')

color      Black and White  Color  Total
duration
7.0                      0      2      2
11.0                     0      1      1
14.0                     0      1      1
20.0                     0      1      1
22.0                     0      6      6
...                    ...    ...    ...
325.0                    0      1      1
330.0                    0      1      1
334.0                    0      1      1
511.0                    0      1      1
Total                  209   4801   5010

[191 rows x 3 columns]

### 5. Average number of likes per director (assuming that total film's likes are counted as a sum of actor's likes)

In [32]:
pd.crosstab(movie.director_facebook_likes, movie.director_name, margins=True, margins_name='Total')

director_name,A. Raven Cruz,Aaron Hann,Aaron Schneider,Aaron Seltzer,Abel Ferrara,Adam Brooks,Adam Carolla,Adam Goldberg,Adam Green,Adam Jay Epstein,...,Zack Ward,Zackary Adler,Zak Penn,Zal Batmanglij,Zoran Lisinac,Álex de la Iglesia,Émile Gaudreault,Éric Tessier,Étienne Faure,Total
director_facebook_likes,,,,,,,,,,,,,,,,,,,,,
0.0,1,1,0,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,907
2.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,63
3.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,70
4.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,60
5.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20000.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
21000.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
22000.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,8
23000.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
Total,1,1,1,1,1,1,1,1,1,1,...,1,1,1,2,1,1,1,1,1,4939